In [18]:
pwd

'/root/Notebooks/Deformable Convolution V2/ops_copy/src'

In [1]:
import torch
import modulated_deform_conv_cuda  
import numpy as np

In [2]:
img = torch.rand([2,3,6,6]).cuda()

In [3]:
offset = torch.ones([2,18,6,6]).cuda()
mask = torch.ones([2,9,6,6]).cuda()

In [4]:
col = torch.zeros([27,2,6,6]).cuda()

In [5]:
#     at::Tensor data_im, 
#     at::Tensor data_offset,
#     at::Tensor data_mask,
#     at::Tensor data_col,
#     int kernel_h, int kernel_w,
#     int pad_h, int pad_w,
#     int stride_h, int stride_w,
#     int dilation_h, int dilation_w,
#     int deformable_group) 

In [19]:
result = modulated_deform_conv_cuda.forward(img, offset, mask, col, 3, 3, 1, 1, 1, 1, 1, 1, 1)

In [20]:
grad_im = torch.zeros_like(img, dtype=torch.float32).to(img.device)
grad_offset = torch.zeros_like(offset, dtype=torch.float32).to(offset.device)
grad_mask = torch.zeros_like(mask, dtype=torch.float32).to(mask.device)

In [21]:
grad_col = torch.rand_like(col)

In [23]:
modulated_deform_conv_cuda.backward(img, offset, mask, grad_col, 
                    3, 3, 1, 1, 1, 1, 1, 1, 1,
                    grad_offset, grad_mask, grad_im)

1

In [26]:
grad_offset

tensor([[[[-0.2864, -0.3891,  0.6995, -0.6489, -0.3659, -0.4455],
          [ 0.2516,  0.0732, -0.1872, -0.3347,  1.0863,  0.1824],
          [-0.4033,  0.1884,  0.0574,  0.0648,  0.1273,  0.1334],
          [ 0.7876, -0.0714, -0.7290,  0.3984, -0.5367, -0.3966],
          [ 0.4834,  0.2245,  0.1999, -0.1251, -0.0297, -0.0499],
          [-1.8848, -0.8987, -1.1670, -0.4571, -0.7097, -0.2224]],

         [[-0.0826, -0.6237,  0.7208,  0.2480,  0.0096, -1.3715],
          [ 0.1439,  0.7586, -0.8772, -0.2177,  0.1763, -0.6094],
          [-0.2488,  0.3366, -0.4465,  0.5134, -0.4300, -0.9739],
          [ 0.3348,  0.4825, -0.6065,  0.7538, -0.6053, -0.8173],
          [-0.2992,  0.1201,  0.4602, -0.0571, -0.5411, -0.4397],
          [-0.2264,  0.0449, -0.8892,  1.0429, -0.2043, -0.2224]],

         [[-0.1063,  1.0631, -0.1194, -1.3477, -0.3416,  0.0000],
          [ 0.2456, -0.4220,  0.2207,  0.6899,  0.0719,  0.0000],
          [ 0.2179,  0.2117,  0.0281,  0.1153, -0.0688,  0.0000],
      

In [6]:
img[0]

tensor([[[0.1065, 0.1377, 0.5139, 0.8681, 0.9206, 0.4225],
         [0.3049, 0.1312, 0.9345, 0.7960, 0.5530, 0.7871],
         [0.7915, 0.5238, 0.3375, 0.2995, 0.5307, 0.5305],
         [0.0206, 0.2244, 0.9618, 0.3667, 0.6654, 0.3499],
         [0.9681, 0.6225, 0.7942, 0.7679, 0.8798, 0.2859],
         [0.9642, 0.6367, 0.8205, 0.0693, 0.8232, 0.3083]],

        [[0.2476, 0.3958, 0.0801, 0.9400, 0.9459, 0.6585],
         [0.0846, 0.2613, 0.7220, 0.0317, 0.2515, 0.3099],
         [0.3472, 0.3917, 0.5485, 0.3704, 0.8156, 0.5313],
         [0.4430, 0.3687, 0.7306, 0.8177, 0.8916, 0.3681],
         [0.0163, 0.6686, 0.0284, 0.8540, 0.5586, 0.4535],
         [0.4107, 0.3781, 0.2240, 0.0379, 0.1877, 0.2276]],

        [[0.9961, 0.8576, 0.2632, 0.3266, 0.8300, 0.9164],
         [0.5149, 0.4816, 0.8923, 0.4613, 0.3438, 0.4286],
         [0.5371, 0.2518, 0.9694, 0.4418, 0.8895, 0.4850],
         [0.1345, 0.8454, 0.9252, 0.3346, 0.9699, 0.8028],
         [0.3559, 0.2801, 0.9839, 0.5150, 0.2896, 0.

In [7]:
col.shape

torch.Size([27, 2, 6, 6])

In [8]:
col[:,0,0,0]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.1312, 0.7960, 0.0000, 0.2244, 0.3667,
        0.0000, 0.0000, 0.0000, 0.0000, 0.2613, 0.0317, 0.0000, 0.3687, 0.8177,
        0.0000, 0.0000, 0.0000, 0.0000, 0.4816, 0.4613, 0.0000, 0.8454, 0.3346],
       device='cuda:0')

In [50]:
col[:,0,0,0]

tensor([0.0597, 0.2637, 0.3745, 0.2913, 0.6735, 0.6048, 0.2769, 0.6832, 0.6631,
        0.1840, 0.2697, 0.1990, 0.2663, 0.3542, 0.2575, 0.2850, 0.4011, 0.1942,
        0.2457, 0.2826, 0.2372, 0.4405, 0.6431, 0.6511, 0.2665, 0.6212, 0.7830],
       device='cuda:0')

In [9]:
col[:,0,0,1]

tensor([0.0000, 0.0000, 0.0000, 0.3049, 0.9345, 0.5530, 0.0206, 0.9618, 0.6654,
        0.0000, 0.0000, 0.0000, 0.0846, 0.7220, 0.2515, 0.4430, 0.7306, 0.8916,
        0.0000, 0.0000, 0.0000, 0.5149, 0.8923, 0.3438, 0.1345, 0.9252, 0.9699],
       device='cuda:0')

In [10]:
col[:,0,2,2]

tensor([0.1312, 0.7960, 0.7871, 0.2244, 0.3667, 0.3499, 0.6367, 0.0693, 0.3083,
        0.2613, 0.0317, 0.3099, 0.3687, 0.8177, 0.3681, 0.3781, 0.0379, 0.2276,
        0.4816, 0.4613, 0.4286, 0.8454, 0.3346, 0.8028, 0.9432, 0.3564, 0.4643],
       device='cuda:0')

In [11]:
bilinear_interpolate(im, 0.5,0.5)

NameError: name 'bilinear_interpolate' is not defined

In [68]:
def pad_with(vector, pad_width, iaxis, kwargs):
...     pad_value = kwargs.get('padder', 10)
...     vector[:pad_width[0]] = pad_value
...     vector[-pad_width[1]:] = pad_value
...     return vector

In [63]:
im = img[0].detach().cpu().numpy()

In [77]:
im.shape

(3, 6, 6)

In [85]:
padded = np.pad(im, ((0,0), (1, 1), (1, 1)), 'constant')

ValueError: Unable to create correctly shaped tuple from ((0, 0), (1, 1), (1, 1))

In [84]:
col[:,0,0,0]

tensor([0.0597, 0.2637, 0.3745, 0.2913, 0.6735, 0.6048, 0.2769, 0.6832, 0.6631,
        0.1840, 0.2697, 0.1990, 0.2663, 0.3542, 0.2575, 0.2850, 0.4011, 0.1942,
        0.2457, 0.2826, 0.2372, 0.4405, 0.6431, 0.6511, 0.2665, 0.6212, 0.7830],
       device='cuda:0')

In [82]:
padded[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.23880571, 0.8160617 , 0.6819017 , 0.0588966 ,
        0.5478447 , 0.61616045, 0.        ],
       [0.        , 0.9264439 , 0.71270204, 0.20834982, 0.6339436 ,
        0.3174246 , 0.5405952 , 0.        ],
       [0.        , 0.18130863, 0.91231525, 0.8190987 , 0.66696554,
        0.74520516, 0.7733555 , 0.        ],
       [0.        , 0.51047856, 0.4379248 , 0.87695116, 0.659516  ,
        0.5116177 , 0.66468805, 0.        ],
       [0.        , 0.31944937, 0.7973489 , 0.5839149 , 0.79996914,
        0.7482772 , 0.9506202 , 0.        ],
       [0.        , 0.2749464 , 0.88281316, 0.33416134, 0.9372135 ,
        0.4178655 , 0.4385736 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]], dtype=float32)

In [120]:
bilinear_interpolate(padded[0], 2.5,1.5)

0.6047538071870804

In [60]:
im = np.array([[0.2388, 0.8161, 0.6819, 0.0589, 0.5478, 0.6162],
         [0.9264, 0.7127, 0.2083, 0.6339, 0.3174, 0.5406],
         [0.1813, 0.9123, 0.8191, 0.6670, 0.7452, 0.7734],
         [0.5105, 0.4379, 0.8770, 0.6595, 0.5116, 0.6647],
         [0.3194, 0.7973, 0.5839, 0.8000, 0.7483, 0.9506],
         [0.2749, 0.8828, 0.3342, 0.9372, 0.4179, 0.4386]])

In [57]:
def bilinear_interpolate(im, x, y):
    x = np.asarray(x)
    y = np.asarray(y)

    x0 = np.floor(x).astype(int)
    x1 = x0 + 1
    y0 = np.floor(y).astype(int)
    y1 = y0 + 1

    x0 = np.clip(x0, 0, im.shape[1]-1);
    x1 = np.clip(x1, 0, im.shape[1]-1);
    y0 = np.clip(y0, 0, im.shape[0]-1);
    y1 = np.clip(y1, 0, im.shape[0]-1);

    Ia = im[ y0, x0 ]
    Ib = im[ y1, x0 ]
    Ic = im[ y0, x1 ]
    Id = im[ y1, x1 ]

    wa = (x1-x) * (y1-y)
    wb = (x1-x) * (y-y0)
    wc = (x-x0) * (y1-y)
    wd = (x-x0) * (y-y0)

    return wa*Ia + wb*Ib + wc*Ic + wd*Id